name    'gmason-zfs'
version '2.0.0'
source 'https://gitlab.msu.edu/gmason/puppet-zfs'
author 'gmason'
license 'GPLv3'
summary 'ZFS Puppet module'
description 'This module installs ZFS from http://zfsonlinux.org/ on Linux hosts. It does not manage pools, just the kernel-level support. It requires EPEL to be installed on the system, but does not have opinions on how you do that. RHEL/CentOS/Scientific Linux 7 support is currently incomplete.'
project_page 'https://gitlab.msu.edu/gmason/puppet-zfs'
