name    'gmason-zfs'
version '0.2.0'
source 'https://git.phd.msu.edu/gmason/puppet-zfs'
author 'gmason'
license 'GPLv3'
summary 'ZFS Puppet module'
description 'This module installs ZFS from http://zfsonlinux.org/ on Linux hosts. It does not manage pools, just the kernel-level support.'
project_page 'https://git.phd.msu.edu/gmason/puppet-zfs'

dependency 'nono/dkms', '>= 0.0.1'
