name    'gmason-zfs'
version '1.0.0'
source 'https://gitlab.msu.edu/gmason/puppet-zfs'
author 'gmason'
license 'GPLv3'
summary 'ZFS Puppet module'
description 'This module installs ZFS from http://zfsonlinux.org/ on Linux hosts. It does not manage pools, just the kernel-level support.'
project_page 'https://gitlab.msu.edu/gmason/puppet-zfs'

dependency 'gmason/dkms', '>= 0.0.3'
